# @API_URL = http://localhost:3000/api
@API_URL = https://radiant-retreat-97282.herokuapp.com/api
@id = 61a2a0b613273118c43432db
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mjc0NTEwMzVlZGFhNjBkZDQ5N2M1MWMiLCJyb2xlIjoiYWRtaW4iLCJwaWMiOiJhc3NldHMvaW1nL2RlZmF1bHQtYXZhdGFyLnBuZyIsImlhdCI6MTY1NTQ1NjEzNywiZXhwIjoxNjU1NDYzMzM3fQ.OLYuFWOwvPw1Kw-ZHa5JslyyfB_KshGfgVnlzQ1A80A
@classname = Hawkers

##################################################################

### CHECK SUBSCRIPTION

GET {{API_URL}}/
Content-Type: application/json

### REGISTER USER

POST {{API_URL}}/register
Content-Type: application/json

{
    "fullname": "Kelvin Morrison",
    "password": "fridge",
    "phonenumber": "0550653404",
    "email": "kelvin@demo.com"
}

### USER LOGIN

POST {{API_URL}}/authenticate
Content-Type: application/json

{
    "email": "jasonaddy51@gmail.com",
    "password": "admin2"
}

### GET USER DATA

GET {{API_URL}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

### GET USER BY ID

GET {{API_URL}}/users/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}


##################################################################

### GET MEMBERS BY CLASSNAME

GET {{API_URL}}/user/members/classname/{{classname}}
Content-Type: application/json
Authorization: Bearer {{token}}


##################################################################

### POST PAYMENT

POST {{API_URL}}/user/payment/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userid": "61be0575b7d178134c8f2643",
    "modeOfPayment": "Momo",
    "subscription_plan": "61c0b5638e498b214820e103",
    "currencyCode": "$",
    "phone_number": "0550653404",
    "type": "Monthly",
    "description": "Payment for 1 month"
}

##################################################################

### GET PAYMENT

GET {{API_URL}}/user/payment
Content-Type: application/json
Authorization: Bearer {{token}}

##################################################################

### GET RESET PASSWORD

GET {{API_URL}}/reset-password/admin@demo.com
Content-Type: application/json

##################################################################

### POST PLAN

POST {{API_URL}}/plan/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Premium Plan",
    "price_per_month": 150,
    "price_per_year": 1600
}

##################################################################

### GET TOTAL USERS

GET {{API_URL}}/allusers/users
Content-Type: application/json
Authorization: Bearer {{token}}

##################################################################

### GET TOTAL ADMINS

GET {{API_URL}}/allusers/admin
Content-Type: application/json
Authorization: Bearer {{token}}

##################################################################

### POST TASK

POST {{API_URL}}/user/task/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "startdate": "2021-12-24T00:00:00.000Z",
  "_id": "61c5aace8f2f0c1c046d651d",
  "userid": "61bdcc37430c743864898cf6",
  "classname": "Admin",
  "name": "Test Tasks 2",
  "description": "This task has to change it's state when it's 2:00",
  "status": "Completed",
  "enddate": "2021-12-24T16:53:00.000Z"
}

##################################################################

### GET PAYMENT DAILY SUMMARY

GET {{API_URL}}/user/payments/summary/daily
Content-Type: application/json
Authorization: Bearer {{token}}

##################################################################

### GET PAYMENT MONTHLY SUMMARY

GET {{API_URL}}/user/payments/summary/monthly
Content-Type: application/json
Authorization: Bearer {{token}}

##################################################################

### GET PAYMENT YEARLY SUMMARY

GET {{API_URL}}/user/payments/summary/yearly
Content-Type: application/json
Authorization: Bearer {{token}}

##################################################################

### GET ALL PAYMENTS

GET {{API_URL}}/user/payment
Content-Type: application/json
Authorization: Bearer {{token}}

##################################################################

### GET ALL ATTENDANCE WITH CLASSNAME PRESENT

GET {{API_URL}}/user/allattendance/present/ABBA
Content-Type: application/json
Authorization: Bearer {{token}}

##################################################################

### GET ALL STUDENTS

GET {{API_URL}}/students
Content-Type: application/json
Authorization: Bearer {{token}}

### GET ALL STUDENTS

GET {{API_URL}}/allstudentsdatefilter/2022-05-03/2022-05-21
Content-Type: application/json
Authorization: Bearer {{token}}

